export const blogPosts = [
    {
        id: 1,
        title: 'በ2018 ምርጥ የፍለጋ ማስታወቂያዎች እና የንጽጽር አስተዳደር ሶፍትዌር',
        slug: 'best-search-ads-comparison-software-2026',
        excerpt: 'በ2018 ታይነትዎን ለመጨመር እና ቀጥተኛ ሽያጭን ለማሳደግ የሚረዱ ምርጥ የፍለጋ ማስታወቂያዎች እና የንጽጽር መሳሪያዎችን ይረዱ።',
        date: 'ታህሳስ 23, 2018',
        readTime: 'የ15 ደቂቃ ንባብ',
        category: 'የንግድ ቴክኖሎጂ',
        image: '/blog/image.png',
        featured: true,
        author: {
            name: 'ማየላ ሎዛኖ',
            avatar: '/avatars/mayela.jpg',
        },
    },
    {
        id: 2,
        title: 'በ2018 የሽያጭ እና የቀጠሮ መያዣ ሶፍትዌሮች',
        slug: '10-best-appointment-sales-software-2026',
        excerpt: 'ለ2018 ምርጥ የሽያጭ እና የቀጠሮ መያዣ ሶፍትዌር እየፈለጉ ነው? ለስራዎ የሚስማማውን ለመለየት 10 መሳሪያዎችን ያነጻጽሩ።',
        date: 'ታህሳስ 11, 2017',
        readTime: 'የ12 ደቂቃ ንባብ',
        category: 'የመስመር ላይ ሽያጭ',
        image: '/image copy 7.png',
        featured: false,
        author: {
            name: 'ሳራ ጆንሰን',
            avatar: '/avatars/sarah.jpg',
        },
    },
    {
        id: 3,
        title: 'ምርጥ የደንበኛ ተሞክሮ አስተዳደር ሶፍትዌር',
        slug: 'best-customer-experience-software',
        excerpt: 'የደንበኛ ጥያቄዎችን፣ አስተያየቶችን እና ግንኙነቶችን የሚያስተዳድሩበት ምርጥ ሶፍትዌር ያግኙ። ለላቀ አገልግሎት የሚሆኑ 10 ምርጥ መድረኮችን ይመልከቱ።',
        date: 'ታህሳስ 10, 2017',
        readTime: 'የ10 ደቂቃ ንባብ',
        category: 'የንግድ አስተዳደር',
        image: '/image copy 8.png',
        featured: false,
        author: {
            name: 'ማይክል ቼን',
            avatar: '/avatars/michael.jpg',
        },
    },
    {
        id: 4,
        title: 'ኤአይ (AI) የንግድ ስራዎችን እንዴት እየቀየረ ነው?',
        slug: 'ai-transforming-business-operations-2026',
        excerpt: 'አርቴፊሻል ኢንተለጀንስ ከአውቶማቲክ ምዝገባ እስከ ግላዊ የደንበኛ ተሞክሮ ድረስ የንግድ አስተዳደርን እንዴት እያሻሻለ እንደሆነ ይረዱ።',
        date: 'ታህሳስ 09, 2017',
        readTime: 'የ8 ደቂቃ ንባብ',
        category: 'የንግድ ቴክኖሎጂ',
        image: '/image copy 9.png',
        featured: false,
        author: {
            name: 'ኤሚሊ ሮድሪጌዝ',
            avatar: '/avatars/emily.jpg',
        },
    },
    {
        id: 5,
        title: 'ለትናንሽ ንግዶች የገቢ አስተዳደር ስልቶች',
        slug: 'revenue-management-strategies-small-businesses',
        excerpt: 'ትናንሽ እና ገለልተኛ ንግዶች ትርፋማነታቸውን ለማሳደግ ሊተገብሯቸው የሚችሏቸው የተረጋገጡ የገቢ አስተዳደር ዘዴዎችን ይማሩ።',
        date: 'ታህሳስ 08, 2017',
        readTime: 'የ11 ደቂቃ ንባብ',
        category: 'የገቢ አስተዳደር',
        image: '/image copy 10.png',
        featured: false,
        author: {
            name: 'ዳዊት ፓርክ',
            avatar: '/avatars/david.jpg',
        },
    },
    {
        id: 6,
        title: 'የብዙ-ቻናል አስተዳደር የተሟላ መመሪያ',
        slug: 'complete-guide-multi-channel-management',
        excerpt: 'የንግድዎን ታይነት እና ሽያጭ በሁሉም መድረኮች ላይ ለማሳደግ የተለያዩ የማከፋፈያ ቻናሎችን የማስተዳደር ጥበብን ይቆጣጠሩ።',
        date: 'ታህሳስ 07, 2017',
        readTime: 'የ14 ደቂቃ ንባብ',
        category: 'የመስመር ላይ ሽያጭ',
        image: '/image-copy-11-no-money.png',
        featured: false,
        author: {
            name: 'ሊዛ ቶምፕሰን',
            avatar: '/avatars/lisa.jpg',
        },
    },
    {
        id: 7,
        title: 'የ2018 የቢዝነስ ሳይበር ደህንነት ምርጥ ተሞክሮዎች',
        slug: 'business-cybersecurity-best-practices-2026',
        excerpt: 'እያንዳንዱ የንግድ ባለቤት ሊተገብራቸው በሚገቡ በእነዚህ አስፈላጊ የሳይበር ደህንነት እርምጃዎች የንግድዎን እና የደንበኞችዎን መረጃ ይጠብቁ።',
        date: 'ታህሳስ 06, 2017',
        readTime: 'የ9 ደቂቃ ንባብ',
        category: 'የንግድ ቴክኖሎጂ',
        image: '/image copy 12.png',
        featured: false,
        author: {
            name: 'ጄምስ ዊልሰን',
            avatar: '/avatars/james.jpg',
        },
    },
    {
        id: 8,
        title: 'ገቢን የሚጨምሩ ዘላቂ የንግድ ልምዶች',
        slug: 'sustainable-business-practices-increase-revenue',
        excerpt: 'ዘላቂ አሠራሮችን መተግበር ወጪን እንዴት እንደሚቀንስ፣ ደንበኞችን እንደሚስብ እና ትርፍዎን እንደሚያሳድግ ይረዱ።',
        date: 'ታህሳስ 05, 2017',
        readTime: 'የ10 ደቂቃ ንባብ',
        category: 'የንግድ አስተዳደር',
        image: '/image-copy-13-no-money.png',
        featured: false,
        author: {
            name: 'ማሪያ ጋርሲያ',
            avatar: '/avatars/maria.jpg',
        },
    },
    {
        id: 9,
        title: 'ዲጂታል ምዝገባ፦ የደንበኛ ተሞክሮ የወደፊት ዕጣ ፈንታ',
        slug: 'digital-registration-future-customer-experience',
        excerpt: 'ዲጂታል ምዝገባ ለዘመናዊ ንግዶች ለምን አስፈላጊ እየሆነ እንደመጣ እና እንዴት በተሳካ ሁኔታ መተግበር እንደሚቻል ይማሩ።',
        date: 'ታህሳስ 04, 2017',
        readTime: 'የ7 ደቂቃ ንባብ',
        category: 'የደንበኛ ተሞክሮ',
        image: '/image copy 14.png',
        featured: false,
        author: {
            name: 'አሌክስ ኩመር',
            avatar: '/avatars/alex.jpg',
        },
    },
];

export const blogCategories = [
    { name: 'ሁሉንም ጽሁፎች', slug: 'all', count: 9 },
    { name: 'የንግድ ቴክኖሎጂ', slug: 'የንግድ ቴክኖሎጂ', count: 3 },
    { name: 'የመስመር ላይ ሽያጭ', slug: 'የመስመር ላይ ሽያጭ', count: 2 },
    { name: 'የንግድ አስተዳደር', slug: 'የንግድ አስተዳደር', count: 2 },
    { name: 'የገቢ አስተዳደር', slug: 'የገቢ አስተዳደር', count: 1 },
    { name: 'የደንበኛ ተሞክሮ', slug: 'የደንበኛ ተሞክሮ', count: 1 },
];
