export const blogPosts = [
    {
        id: 1,
        title: 'Best Search Ads & Comparison Software In 2026',
        slug: 'best-search-ads-comparison-software-2026',
        excerpt: 'Discover the top search ads and comparison tools that help you maximize visibility and drive direct sales in 2026.',
        date: 'January 02, 2026',
        readTime: '15 min read',
        category: 'Business Technology',
        image: '/blog/image.png',
        featured: true,
        author: {
            name: 'Abel Ashine',
            avatar: '/avatars/mayela.jpg',
        },
    },
    {
        id: 2,
        title: '10 Best Appointment & Sales Software in 2026',
        slug: '10-best-appointment-sales-software-2026',
        excerpt: 'Looking for the best sales and appointment software for 2026? Compare 10 tools side by side to see which one fits your operations best.',
        date: 'December 20, 2025',
        readTime: '12 min read',
        category: 'Online Sales',
        image: '/image copy 7.png',
        featured: false,
        author: {
            name: 'Ebisa Fufi',
            avatar: '/avatars/sarah.jpg',
        },
    },
    {
        id: 3,
        title: 'Best Customer Experience Software',
        slug: 'best-customer-experience-software',
        excerpt: 'Find the best customer experience software to manage requests, feedback, and communication. See the 10 best platforms for superior service.',
        date: 'December 19, 2025',
        readTime: '10 min read',
        category: 'Business Management',
        image: '/image copy 8.png',
        featured: false,
        author: {
            name: 'Yitbarek Alemu',
            avatar: '/avatars/michael.jpg',
        },
    },
    {
        id: 4,
        title: 'How AI is Transforming Business Operations in 2026',
        slug: 'ai-transforming-business-operations-2026',
        excerpt: 'Explore how artificial intelligence is revolutionizing business management, from automated registration to personalized customer experiences.',
        date: 'December 18, 2025',
        readTime: '8 min read',
        category: 'Business Technology',
        image: '/image copy 9.png',
        featured: false,
        author: {
            name: 'Ebisa Fufi',
            avatar: '/avatars/emily.jpg',
        },
    },
    {
        id: 5,
        title: 'Revenue Management Strategies for Small Businesses',
        slug: 'revenue-management-strategies-small-businesses',
        excerpt: 'Learn proven revenue management techniques that small and independent businesses can implement to maximize profitability.',
        date: 'December 17, 2025',
        readTime: '11 min read',
        category: 'Revenue Management',
        image: '/image copy 10.png',
        featured: false,
        author: {
            name: 'Ebisa Fufi   ',
            avatar: '/avatars/david.jpg',
        },
    },
    {
        id: 6,
        title: 'Complete Guide to Multi-Channel Management',
        slug: 'complete-guide-multi-channel-management',
        excerpt: 'Master the art of managing multiple distribution channels to increase your business visibility and sales across all platforms.',
        date: 'December 16, 2025',
        readTime: '14 min read',
        category: 'Online Sales',
        image: '/image-copy-11-no-money.png',
        featured: false,
        author: {
            name: 'Abel Ashine',
            avatar: '/avatars/lisa.jpg',
        },
    },
    {
        id: 7,
        title: 'Business Cybersecurity Best Practices for 2026',
        slug: 'business-cybersecurity-best-practices-2026',
        excerpt: 'Protect your business and customer data with these essential cybersecurity measures every business owner should implement.',
        date: 'December 15, 2025',
        readTime: '9 min read',
        category: 'Business Technology',
        image: '/image copy 12.png',
        featured: false,
        author: {
            name: 'Abel Ashine',
            avatar: '/avatars/james.jpg',
        },
    },
    {
        id: 8,
        title: 'Sustainable Business Practices That Increase Revenue',
        slug: 'sustainable-business-practices-increase-revenue',
        excerpt: 'Discover how implementing sustainable practices can reduce costs, attract eco-conscious customers, and boost your bottom line.',
        date: 'December 14, 2025',
        readTime: '10 min read',
        category: 'Business Management',
        image: '/image-copy-13-no-money.png',
        featured: false,
        author: {
            name: 'Kiya',
            avatar: '/avatars/maria.jpg',
        },
    },
    {
        id: 9,
        title: 'Digital Registration: The Future of Customer Experience',
        slug: 'digital-registration-future-customer-experience',
        excerpt: 'Learn why digital registration is becoming essential for modern businesses and how to implement it successfully.',
        date: 'December 13, 2025',
        readTime: '7 min read',
        category: 'Customer Experience',
        image: '/image copy 14.png',
        featured: false,
        author: {
            name: 'Yitbarek Alemu',
            avatar: '/avatars/alex.jpg',
        },
    },
];

export const blogCategories = [
    { name: 'All Posts', slug: 'all', count: 9 },
    { name: 'Business Technology', slug: 'Business Technology', count: 3 },
    { name: 'Online Sales', slug: 'Online Sales', count: 2 },
    { name: 'Business Management', slug: 'Business Management', count: 2 },
    { name: 'Revenue Management', slug: 'Revenue Management', count: 1 },
    { name: 'Customer Experience', slug: 'Customer Experience', count: 1 },
];
