export const blogPosts = [
    {
        id: 1,
        title: 'እ.ኤ.አ. በ 2026 ምርጡ የሆቴል ሜታሰርች ማኔጅመንት ሶፍትዌር',
        slug: 'best-hotel-metasearch-management-software-2026',
        excerpt: 'በ 2026 ታይነትን ለመጨመር እና ቀጥተኛ ቦታ ማስያዝን ለማሳደግ የሚረዱ ምርጥ የሆቴል ሜታሰርች ማኔጅመንት መሳሪያዎችን ይወቁ።',
        date: 'ታህሳስ 24 ቀን 2018',
        readTime: 'የ15 ደቂቃ ንባብ',
        category: 'የሆቴል ቴክኖሎጂ',
        image: '/blog/image.png',
        featured: true,
        author: {
            name: 'ማየላ ሎዛኖ',
            avatar: '/avatars/mayela.jpg',
        },
    },
    {
        id: 2,
        title: 'በ 2026 10 ምርጥ የሆቴል ማስያዣ ሶፍትዌሮች',
        slug: '10-best-hotel-reservation-software-2026',
        excerpt: 'ለ 2026 ምርጡን የሆቴል ማስያዣ ሶፍትዌር እየፈለጉ ነው? ለስራዎ የትኛው በተሻለ ሁኔታ እንደሚስማማ ለማየት 10 መሳሪያዎችን ጎን ለጎን ያወዳድሩ።',
        date: 'ታህሳስ 11 ቀን 2018',
        readTime: 'የ12 ደቂቃ ንባብ',
        category: 'የመስመር ላይ ቦታ ማስያዝ',
        image: '/image copy 7.png',
        featured: false,
        author: {
            name: 'ሳራ ጆንሰን',
            avatar: '/avatars/sarah.jpg',
        },
    },
    {
        id: 3,
        title: 'ምርጥ የሆቴል እንግዳ ተሞክሮ ሶፍትዌር',
        slug: 'best-hotel-guest-experience-software',
        excerpt: 'የእንግዳ ጥያቄዎችን፣ ግብረመልሶችን እና ግንኙነቶችን ለማስተዳደር ምርጡን የሆቴል እንግዳ ተሞክሮ ሶፍትዌር ያግኙ።',
        date: 'ታህሳስ 10 ቀን 2018',
        readTime: 'የ10 ደቂቃ ንባብ',
        category: 'የሆቴል አስተዳደር',
        image: '/image copy 8.png',
        featured: false,
        author: {
            name: 'ማይክል ቼን',
            avatar: '/avatars/michael.jpg',
        },
    },
    {
        id: 4,
        title: 'ኤአይ (AI) በ 2026 የሆቴል ስራዎችን እንዴት እንደሚለውጥ',
        slug: 'ai-transforming-hotel-operations-2026',
        excerpt: 'አርቴፊሻል ኢንተለጀንስ ከአውቶማቲክ ቼክ-ኢን እስከ ግላዊ የእንግዳ ተሞክሮዎች ድረስ የሆቴል አስተዳደርን እንዴት አብዮት እያደረገ እንደሆነ ይወቁ።',
        date: 'ታህሳስ 09 ቀን 2018',
        readTime: 'የ8 ደቂቃ ንባብ',
        category: 'የሆቴል ቴክኖሎጂ',
        image: '/image copy 9.png',
        featured: false,
        author: {
            name: 'ኤሚሊ ሮድሪጌዝ',
            avatar: '/avatars/emily.jpg',
        },
    },
    {
        id: 5,
        title: 'ለአነስተኛ ሆቴሎች የገቢ አስተዳደር ስልቶች',
        slug: 'revenue-management-strategies-small-hotels',
        excerpt: 'አነስተኛ እና ገለልተኛ ሆቴሎች ትርፋማነትን ለመጨመር ሊተገበሯቸው የሚችሉ የተረጋገጡ የገቢ አስተዳደር ቴክኒኮችን ይማሩ።',
        date: 'ታህሳስ 08 ቀን 2018',
        readTime: 'የ11 ደቂቃ ንባብ',
        category: 'የገቢ አስተዳደር',
        image: '/image copy 10.png',
        featured: false,
        author: {
            name: 'ዳዊት ፓርክ',
            avatar: '/avatars/david.jpg',
        },
    },
    {
        id: 6,
        title: 'የሆቴል ቻናል ማኔጅመንት የተሟላ መመሪያ',
        slug: 'complete-guide-hotel-channel-management',
        excerpt: 'የሆቴልዎን ታይነት እና ቦታ ማስያዝ በሁሉም መድረኮች ላይ ለመጨመር ብዙ የሽያጭ ቻናሎችን የማስተዳደር ጥበብን ይቆጣጠሩ።',
        date: 'ታህሳስ 07 ቀን 2018',
        readTime: 'የ14 ደቂቃ ንባብ',
        category: 'የመስመር ላይ ቦታ ማስያዝ',
        image: '/image copy 11.png',
        featured: false,
        author: {
            name: 'ሊዛ ቶምፕሰን',
            avatar: '/avatars/lisa.jpg',
        },
    },
    {
        id: 7,
        title: 'በ 2026 የሆቴል ሳይበር ደህንነት ምርጥ ልምዶች',
        slug: 'hotel-cybersecurity-best-practices-2026',
        excerpt: 'እያንዳንዱ የሆቴል ባለቤት ሊተገብራቸው በሚገቡ አስፈላጊ የሳይበር ደህንነት እርምጃዎች የሆቴልዎን እና የእንግዳዎን መረጃ ይጠብቁ።',
        date: 'ታህሳስ 06 ቀን 2018',
        readTime: 'የ9 ደቂቃ ንባብ',
        category: 'የሆቴል ቴክኖሎጂ',
        image: '/image copy 12.png',
        featured: false,
        author: {
            name: 'ጄምስ ዊልሰን',
            avatar: '/avatars/james.jpg',
        },
    },
    {
        id: 8,
        title: 'ገቢን የሚጨምሩ ዘላቂ የሆቴል አሠራሮች',
        slug: 'sustainable-hotel-practices-increase-revenue',
        excerpt: 'ዘላቂ የሆኑ አሠራሮችን መተግበር ወጪን እንዴት እንደሚቀንስ፣ ለአካባቢ ተስማሚ የሆኑ ተጓዦችን እንደሚስብ እና ትርፍዎን እንደሚጨምር ይወቁ።',
        date: 'ታህሳስ 05 ቀን 2018',
        readTime: 'የ10 ደቂቃ ንባብ',
        category: 'የሆቴል አስተዳደር',
        image: '/image copy 13.png',
        featured: false,
        author: {
            name: 'ማሪያ ጋርሲያ',
            avatar: '/avatars/maria.jpg',
        },
    },
    {
        id: 9,
        title: 'የሞባይል ቼክ-ኢን፡ የሆቴል እንግዳ ተሞክሮ የወደፊት ዕጣ',
        slug: 'mobile-check-in-future-hotel-guest-experience',
        excerpt: 'የሞባይል ቼክ-ኢን ለዘመናዊ ሆቴሎች ለምን አስፈላጊ እየሆነ እንደመጣ እና እንዴት በተሳካ ሁኔታ መተግበር እንደሚቻል ይማሩ።',
        date: 'ታህሳስ 04 ቀን 2018',
        readTime: 'የ7 ደቂቃ ንባብ',
        category: 'የእንግዳ ተሞክሮ',
        image: '/image copy 14.png',
        featured: false,
        author: {
            name: 'አሌክስ ኩመር',
            avatar: '/avatars/alex.jpg',
        },
    },
];

export const blogCategories = [
    { name: 'ሁሉም ጽሁፎች', slug: 'all', count: 9 },
    { name: 'የሆቴል ቴክኖሎጂ', slug: 'Hotel Technology', count: 3 },
    { name: 'የመስመር ላይ ቦታ ማስያዝ', slug: 'Online Bookings', count: 2 },
    { name: 'የሆቴል አስተዳደር', slug: 'Hotel Management', count: 2 },
    { name: 'የገቢ አስተዳደር', slug: 'Revenue Management', count: 1 },
    { name: 'የእንግዳ ተሞክሮ', slug: 'Guest Experience', count: 1 },
];
