export const blogPosts = [
    {
        id: 1,
        title: 'Best Hotel Metasearch Management Software In 2026',
        slug: 'best-hotel-metasearch-management-software-2026',
        excerpt: 'Discover the top hotel metasearch management tools that help you maximize visibility and drive direct bookings in 2026.',
        date: 'December 20, 2025',
        readTime: '15 min read',
        category: 'Hotel Technology',
        image: '/blog/image.png',
        featured: true,
        author: {
            name: 'Mayela Lozano',
            avatar: '/avatars/mayela.jpg',
        },
    },
    {
        id: 2,
        title: '10 Best Hotel Reservation Software in 2026',
        slug: '10-best-hotel-reservation-software-2026',
        excerpt: 'Looking for the best hotel reservation software for 2026? Compare 10 tools side by side to see which one fits your operations best.',
        date: 'December 20, 2025',
        readTime: '12 min read',
        category: 'Online Bookings',
        image: '/image copy 7.png',
        featured: false,
        author: {
            name: 'Sarah Johnson',
            avatar: '/avatars/sarah.jpg',
        },
    },
    {
        id: 3,
        title: 'Best Hotel Guest Experience Software',
        slug: 'best-hotel-guest-experience-software',
        excerpt: 'Find the best hotel guest experience software to manage guest requests, feedback, and communication. See the 10 best platforms for superior hospitality.',
        date: 'December 19, 2025',
        readTime: '10 min read',
        category: 'Hotel Management',
        image: '/image copy 8.png',
        featured: false,
        author: {
            name: 'Michael Chen',
            avatar: '/avatars/michael.jpg',
        },
    },
    {
        id: 4,
        title: 'How AI is Transforming Hotel Operations in 2026',
        slug: 'ai-transforming-hotel-operations-2026',
        excerpt: 'Explore how artificial intelligence is revolutionizing hotel management, from automated check-ins to personalized guest experiences.',
        date: 'December 18, 2025',
        readTime: '8 min read',
        category: 'Hotel Technology',
        image: '/image copy 9.png',
        featured: false,
        author: {
            name: 'Emily Rodriguez',
            avatar: '/avatars/emily.jpg',
        },
    },
    {
        id: 5,
        title: 'Revenue Management Strategies for Small Hotels',
        slug: 'revenue-management-strategies-small-hotels',
        excerpt: 'Learn proven revenue management techniques that small and independent hotels can implement to maximize profitability.',
        date: 'December 17, 2025',
        readTime: '11 min read',
        category: 'Revenue Management',
        image: '/image copy 10.png',
        featured: false,
        author: {
            name: 'David Park',
            avatar: '/avatars/david.jpg',
        },
    },
    {
        id: 6,
        title: 'Complete Guide to Hotel Channel Management',
        slug: 'complete-guide-hotel-channel-management',
        excerpt: 'Master the art of managing multiple distribution channels to increase your hotel\'s visibility and bookings across all platforms.',
        date: 'December 16, 2025',
        readTime: '14 min read',
        category: 'Online Bookings',
        image: '/image copy 11.png',
        featured: false,
        author: {
            name: 'Lisa Thompson',
            avatar: '/avatars/lisa.jpg',
        },
    },
    {
        id: 7,
        title: 'Hotel Cybersecurity Best Practices for 2026',
        slug: 'hotel-cybersecurity-best-practices-2026',
        excerpt: 'Protect your hotel and guest data with these essential cybersecurity measures every hotelier should implement.',
        date: 'December 15, 2025',
        readTime: '9 min read',
        category: 'Hotel Technology',
        image: '/image copy 12.png',
        featured: false,
        author: {
            name: 'James Wilson',
            avatar: '/avatars/james.jpg',
        },
    },
    {
        id: 8,
        title: 'Sustainable Hotel Practices That Increase Revenue',
        slug: 'sustainable-hotel-practices-increase-revenue',
        excerpt: 'Discover how implementing sustainable practices can reduce costs, attract eco-conscious travelers, and boost your bottom line.',
        date: 'December 14, 2025',
        readTime: '10 min read',
        category: 'Hotel Management',
        image: '/image copy 13.png',
        featured: false,
        author: {
            name: 'Maria Garcia',
            avatar: '/avatars/maria.jpg',
        },
    },
    {
        id: 9,
        title: 'Mobile Check-in: The Future of Hotel Guest Experience',
        slug: 'mobile-check-in-future-hotel-guest-experience',
        excerpt: 'Learn why mobile check-in is becoming essential for modern hotels and how to implement it successfully.',
        date: 'December 13, 2025',
        readTime: '7 min read',
        category: 'Guest Experience',
        image: '/image copy 14.png',
        featured: false,
        author: {
            name: 'Alex Kumar',
            avatar: '/avatars/alex.jpg',
        },
    },
];

export const blogCategories = [
    { name: 'All Posts', slug: 'all', count: 9 },
    { name: 'Hotel Technology', slug: 'Hotel Technology', count: 3 },
    { name: 'Online Bookings', slug: 'Online Bookings', count: 2 },
    { name: 'Hotel Management', slug: 'Hotel Management', count: 2 },
    { name: 'Revenue Management', slug: 'Revenue Management', count: 1 },
    { name: 'Guest Experience', slug: 'Guest Experience', count: 1 },
];
