export const newsArticles = [
    {
        id: 1,
        title: 'weleba Invites Independent Hoteliers to IHS 2026',
        slug: 'weleba-invites-independent-hoteliers-ihs-2026',
        excerpt: 'Join us at the International Hotel Show 2026 to discover how weleba is revolutionizing hotel management for independent properties.',
        content: 'Full article content here...',
        date: 'January 2, 2026',
        publishedAt: '2026-01-02',
        readTime: '3 min read',
        category: 'Company News',
        image: '/image copy 10.png',
        featured: true,
        author: {
            name: 'weleba Team',
            role: 'Marketing',
        },
    },
    {
        id: 2,
        title: 'weleba Launches AI-Powered Revenue Intelligence',
        slug: 'weleba-launches-ai-powered-revenue-intelligence',
        excerpt: 'Our new AI-driven revenue management system helps hotels optimize pricing in real-time based on market demand and competitor analysis.',
        content: 'Full article content here...',
        date: 'December 28, 2025',
        publishedAt: '2025-12-28',
        readTime: '5 min read',
        category: 'Product Updates',
        image: '/image copy 11.png',
        featured: true,
        author: {
            name: 'Product Team',
            role: 'Product Management',
        },
    },
    {
        id: 3,
        title: 'weleba Reaches 5,000 Hotel Milestone',
        slug: 'weleba-reaches-5000-hotel-milestone',
        excerpt: 'We\'re proud to announce that over 5,000 hotels worldwide now trust weleba to power their operations.',
        content: 'Full article content here...',
        date: 'December 20, 2025',
        publishedAt: '2025-12-20',
        readTime: '4 min read',
        category: 'Company News',
        image: '/image copy 12.png',
        featured: false,
        author: {
            name: 'weleba Team',
            role: 'Marketing',
        },
    },
    {
        id: 4,
        title: 'New Mobile Check-in Feature Now Available',
        slug: 'new-mobile-check-in-feature-available',
        excerpt: 'Guests can now check in, access digital keys, and manage their stay entirely from their mobile devices.',
        content: 'Full article content here...',
        date: 'December 15, 2025',
        publishedAt: '2025-12-15',
        readTime: '3 min read',
        category: 'Product Updates',
        image: '/image copy 13.png',
        featured: false,
        author: {
            name: 'Product Team',
            role: 'Product Management',
        },
    },
    {
        id: 5,
        title: 'weleba Partners with Leading Payment Processors',
        slug: 'weleba-partners-leading-payment-processors',
        excerpt: 'New integrations with Stripe, Square, and PayPal make payment processing even more seamless for our hotel partners.',
        content: 'Full article content here...',
        date: 'December 10, 2025',
        publishedAt: '2025-12-10',
        readTime: '4 min read',
        category: 'Partnerships',
        image: '/image copy 14.png',
        featured: false,
        author: {
            name: 'Business Development',
            role: 'Partnerships',
        },
    },
    {
        id: 6,
        title: 'Hospitality Industry Trends Report 2026',
        slug: 'hospitality-industry-trends-report-2026',
        excerpt: 'Our annual report reveals key trends shaping the future of hotel technology and guest expectations.',
        content: 'Full article content here...',
        date: 'December 5, 2025',
        publishedAt: '2025-12-05',
        readTime: '8 min read',
        category: 'Industry Insights',
        image: '/image copy 15.png',
        featured: false,
        author: {
            name: 'Research Team',
            role: 'Market Research',
        },
    },
    {
        id: 7,
        title: 'weleba Wins Best Hotel PMS Award 2025',
        slug: 'weleba-wins-best-hotel-pms-award-2025',
        excerpt: 'We\'re honored to receive the Hotel Tech Awards\' Best Property Management System for the third consecutive year.',
        content: 'Full article content here...',
        date: 'November 28, 2025',
        publishedAt: '2025-11-28',
        readTime: '2 min read',
        category: 'Company News',
        image: '/image copy 16.png',
        featured: false,
        author: {
            name: 'weleba Team',
            role: 'Marketing',
        },
    },
    {
        id: 8,
        title: 'Enhanced Security Features Rollout',
        slug: 'enhanced-security-features-rollout',
        excerpt: 'New two-factor authentication and advanced encryption protect your hotel data better than ever.',
        content: 'Full article content here...',
        date: 'November 20, 2025',
        publishedAt: '2025-11-20',
        readTime: '5 min read',
        category: 'Product Updates',
        image: '/image copy 2.png',
        featured: false,
        author: {
            name: 'Security Team',
            role: 'Engineering',
        },
    },
];

export const newsCategories = [
    { name: 'All News', slug: 'all', count: 8 },
    { name: 'Company News', slug: 'Company News', count: 3 },
    { name: 'Product Updates', slug: 'Product Updates', count: 3 },
    { name: 'Partnerships', slug: 'Partnerships', count: 1 },
    { name: 'Industry Insights', slug: 'Industry Insights', count: 1 },
];
export const newsHeroContent = {
    tag: 'News',
    title: 'Latest<br />News &<br />Updates',
    description: 'Stay informed with the latest weleba product updates, company announcements, and hospitality industry news.'
};
