export const newsArticles = [
    {
        id: 1,
        title: 'weleba ገለልተኛ የሆቴል ባለቤቶችን ለ IHS 2026 ይጋብዛል',
        slug: 'weleba-invites-independent-hoteliers-ihs-2026',
        excerpt: 'በዓለም አቀፍ የሆቴል አውደ ርዕይ 2026 ላይ በመገኘት weleba ለገለልተኛ ሆቴሎች የአስተዳደር አብዮት እንዴት እያመጣ እንደሆነ ይወቁ።',
        content: 'ሙሉ ዘገባው እዚህ ይቀርባል...',
        date: 'ታህሳስ 24 ቀን 2018',
        publishedAt: '2026-01-02',
        readTime: 'የ3 ደቂቃ ንባብ',
        category: 'የኩባንያ ዜና',
        image: '/image copy 10.png',
        featured: true,
        author: {
            name: 'የweleba ቡድን',
            role: 'ማርኬቲንግ',
        },
    },
    {
        id: 2,
        title: 'weleba በኤአይ (AI) የሚመራ የገቢ ግንዛቤዎችን አስተዋወቀ',
        slug: 'weleba-launches-ai-powered-revenue-intelligence',
        excerpt: 'አዲሱ በኤአይ የሚመራ የገቢ አስተዳደር ስርዓታችን ሆቴሎች በገበያ ፍላጎት እና በተፎካካሪዎች ትንተና ላይ ተመስርተው የዋጋ ማስተካከያ እንዲያደርጉ ይረዳል።',
        content: 'ሙሉ ዘገባው እዚህ ይቀርባል...',
        date: 'ታህሳስ 19 ቀን 2018',
        publishedAt: '2025-12-28',
        readTime: 'የ5 ደቂቃ ንባብ',
        category: 'የምርት ዜና',
        image: '/image copy 11.png',
        featured: true,
        author: {
            name: 'የምርት ቡድን',
            role: 'የምርት አስተዳደር',
        },
    },
    {
        id: 3,
        title: 'weleba 5,000 ሆቴሎችን ማገልገል ቻለ',
        slug: 'weleba-reaches-5000-hotel-milestone',
        excerpt: 'በዓለም ዙሪያ ከ5,000 በላይ ሆቴሎች ስራቸውን ለማከናወን welebaን እንደሚተማመኑ በደስታ እንገልጻለን።',
        content: 'ሙሉ ዘገባው እዚህ ይቀርባል...',
        date: 'ታህሳስ 11 ቀን 2018',
        publishedAt: '2025-12-20',
        readTime: 'የ4 ደቂቃ ንባብ',
        category: 'የኩባንያ ዜና',
        image: '/image copy 12.png',
        featured: false,
        author: {
            name: 'የweleba ቡድን',
            role: 'ማርኬቲንግ',
        },
    },
    {
        id: 4,
        title: 'አዲስ የሞባይል ቼክ-ኢን አገልግሎት ስራ ጀመረ',
        slug: 'new-mobile-check-in-feature-available',
        excerpt: 'እንግዶች አሁን በሞባይላቸው ቼክ-ኢን ማድረግ፣ የዲጂታል ቁልፍ ማግኘት እና ቆይታቸውን ማስተዳደር ይችላሉ።',
        content: 'ሙሉ ዘገባው እዚህ ይቀርባል...',
        date: 'ታህሳስ 06 ቀን 2018',
        publishedAt: '2025-12-15',
        readTime: 'የ3 ደቂቃ ንባብ',
        category: 'የምርት ዜና',
        image: '/image copy 13.png',
        featured: false,
        author: {
            name: 'የምርት ቡድን',
            role: 'የምርት አስተዳደር',
        },
    },
    {
        id: 5,
        title: 'weleba ከዋና ዋና የክፍያ አገልግሎቶች ጋር ተባባሪ ሆነ',
        slug: 'weleba-partners-leading-payment-processors',
        excerpt: 'ከStripe፣ Square እና PayPal ጋር የተደረጉ አዳዲስ ትስስሮች ለሆቴል ተካፋዮቻችን የክፍያ ሂደቱን የበለጠ ቀላል ያደርጉታል።',
        content: 'ሙሉ ዘገባው እዚህ ይቀርባል...',
        date: 'ታህሳስ 01 ቀን 2018',
        publishedAt: '2025-12-10',
        readTime: 'የ4 ደቂቃ ንባብ',
        category: 'አጋርነት',
        image: '/image copy 14.png',
        featured: false,
        author: {
            name: 'ቢዝነስ ዴቨሎፕመንት',
            role: 'አጋርነት',
        },
    },
    {
        id: 6,
        title: 'የመስተንግዶ ኢንዱስትሪ አዝማሚያዎች ሪፖርት 2026',
        slug: 'hospitality-industry-trends-report-2026',
        excerpt: 'ዓመታዊ ሪፖርታችን የሆቴል ቴክኖሎጂን እና የእንግዳ ፍላጎቶችን የወደፊት ዕጣ ፈንታ የሚወስኑ ዋና ዋና ጉዳዮችን ያሳያል።',
        content: 'ሙሉ ዘገባው እዚህ ይቀርባል...',
        date: 'ህዳር 26 ቀን 2018',
        publishedAt: '2025-12-05',
        readTime: 'የ8 ደቂቃ ንባብ',
        category: 'የኢንዱስትሪ ግንዛቤዎች',
        image: '/image copy 15.png',
        featured: false,
        author: {
            name: 'የጥናት ቡድን',
            role: 'የገበያ ጥናት',
        },
    },
    {
        id: 7,
        title: 'weleba የ2025 ምርጥ የሆቴል PMS ሽልማትን አሸነፈ',
        slug: 'weleba-wins-best-hotel-pms-award-2025',
        excerpt: 'ለሶስተኛ ተከታታይ ዓመት የHotel Tech Awards ምርጥ የሆቴል አስተዳደር ስርዓት ሽልማትን በማግኘታችን ኩራት ይሰማናል።',
        content: 'ሙሉ ዘገባው እዚህ ይቀርባል...',
        date: 'ህዳር 19 ቀን 2018',
        publishedAt: '2025-11-28',
        readTime: 'የ2 ደቂቃ ንባብ',
        category: 'የኩባንያ ዜና',
        image: '/image copy 16.png',
        featured: false,
        author: {
            name: 'የweleba ቡድን',
            role: 'ማርኬቲንግ',
        },
    },
    {
        id: 8,
        title: 'የተሻሻሉ የደህንነት ባህሪያት ስራ ላይ ዋሉ',
        slug: 'enhanced-security-features-rollout',
        excerpt: 'አዲስ ባለ ሁለት ደረጃ ማረጋገጫ (2FA) እና የላቀ ምስጠራ የሆቴልዎን መረጃ ከመቼውም ጊዜ በላይ ይጠብቃሉ።',
        content: 'ሙሉ ዘገባው እዚህ ይቀርባል...',
        date: 'ህዳር 11 ቀን 2018',
        publishedAt: '2025-11-20',
        readTime: 'የ5 ደቂቃ ንባብ',
        category: 'የምርት ዜና',
        image: '/image copy 2.png',
        featured: false,
        author: {
            name: 'የደህንነት ቡድን',
            role: 'ምህንድስና',
        },
    },
];

export const newsCategories = [
    { name: 'ሁሉም ዜናዎች', slug: 'all', count: 8 },
    { name: 'የኩባንያ ዜና', slug: 'Company News', count: 3 },
    { name: 'የምርት ዜና', slug: 'Product Updates', count: 3 },
    { name: 'አጋርነት', slug: 'Partnerships', count: 1 },
    { name: 'የኢንዱስትሪ ግንዛቤዎች', slug: 'Industry Insights', count: 1 },
];

export const newsHeroContent = {
    tag: 'ዜና',
    title: 'የቅርብ ጊዜ<br />ዜናዎች እና<br />ወቅታዊ መረጃዎች',
    description: 'የweleba ምርት ማሻሻያዎችን፣ የኩባንያ መግለጫዎችን እና የመስተንግዶ ኢንዱስትሪ ዜናዎችን እዚህ ያግኙ።'
};
